In [27]:
import pandas as pd
import numpy as np

In [29]:
bestand_naam = "UserReviewsClean43LIWC (1).xlsx"
df = pd.read_excel(bestand_naam)

In [30]:
df.head()

,url,idvscore,reviewer,dateP,Rev,thumbsUp,thumbsTot,WC,Analytic,Clout,...,Comma,Colon,SemiC,QMark,Exclam,Dash,Quote,Apostro,Parenth,OtherP
0,https://www.metacritic.com/movie/bronson,8,'Longbottom94',"'Apr 25, 2013'",'Many have dismissed this film for not explor...,2,2,113,94.05,32.91,...,4.42,0.0,0.0,0.0,0.0,0.88,0,1.77,0.00,0.0
1,https://www.metacritic.com/movie/bronson,9,'MartinB',"'Oct 13, 2009'",'Anyone who doesn t like this movie simply ju...,0,1,103,57.11,38.53,...,0.97,0.0,0.0,0.0,0.0,0.00,0,1.94,5.83,0.0
2,https://www.metacritic.com/movie/bronson,10,'Jaakko',"'Jul 19, 2012'",'Not sure what to think at this film at first...,1,1,143,75.73,66.27,...,0.70,0.0,0.0,0.0,0.0,0.00,0,1.40,0.00,1.4
3,https://www.metacritic.com/movie/bronson,6,'CapoR',"'Oct 13, 2009'",'Nicely portrayed but it lacks the elements t...,0,1,14,83.81,23.75,...,0.00,0.0,0.0,0.0,0.0,0.00,0,14.29,0.00,0.0
4,https://www.metacritic.com/movie/bronson,8,'OrwellB.',"'Oct 10, 2009'",'Bronson is more than entertainment. It is ar...,0,0,20,93.26,69.14,...,0.00,0.0,0.0,0.0,0.0,0.00,0,10.00,0.00,0.0

In [11]:
User_review = df

In [13]:
url_idv_user = User_review[["url","idvscore"]]
print = url_idv_user

In [15]:
url_idv_user.head()

                                        url idvscore
0  https://www.metacritic.com/movie/bronson        8
1  https://www.metacritic.com/movie/bronson        9
2  https://www.metacritic.com/movie/bronson       10
3  https://www.metacritic.com/movie/bronson        6
4  https://www.metacritic.com/movie/bronson        8

In [17]:
user_fil_def = url_idv_user[["url"]].copy()
user_fil_def["idvscore_x10"] = url_idv_user["idvscore"]*10
user_fil_def

                                                   url idvscore_x10
0             https://www.metacritic.com/movie/bronson           80
1             https://www.metacritic.com/movie/bronson           90
2             https://www.metacritic.com/movie/bronson          100
3             https://www.metacritic.com/movie/bronson           60
4             https://www.metacritic.com/movie/bronson           80
...                                                ...          ...
319657  https://www.metacritic.com/movie/spirited-away          100
319658  https://www.metacritic.com/movie/spirited-away          100
319659  https://www.metacritic.com/movie/spirited-away          100
319660  https://www.metacritic.com/movie/spirited-away          100
319661  https://www.metacritic.com/movie/spirited-away          100

[319662 rows x 2 columns]

In [19]:
user_fil_duplicates = user_fil_def.drop_duplicates()
user_fil_duplicates

                                                   url idvscore_x10
0             https://www.metacritic.com/movie/bronson           80
1             https://www.metacritic.com/movie/bronson           90
2             https://www.metacritic.com/movie/bronson          100
3             https://www.metacritic.com/movie/bronson           60
7             https://www.metacritic.com/movie/bronson           70
...                                                ...          ...
319441  https://www.metacritic.com/movie/spirited-away            0
319443  https://www.metacritic.com/movie/spirited-away           10
319444  https://www.metacritic.com/movie/spirited-away           30
319461  https://www.metacritic.com/movie/spirited-away           20
319466  https://www.metacritic.com/movie/spirited-away           60

[50667 rows x 2 columns]

In [21]:
user_fil_def.to_excel("C:\\Users\\gwenr\\OneDrive\\Documenten\\DDB master 24\\user_fil_def2.xlsx")

In [22]:
emptycells = user_fil_def["idvscore_x10"].isna()
emptycells

0         False
1         False
2         False
3         False
4         False
          ...
319657    False
319658    False
319659    False
319660    False
319661    False
Name: idvscore_x10, Length: 319662, dtype: bool

In [25]:
user_fil_duplicates.to_csv("C:\\Users\\gwenr\\OneDrive\\Documenten\\DDB master 24\\user_fil_duplicates", index=False)